# Copyright (c) ModelScope Contributors. All rights reserved.
"""Training-domain descriptors for native-TQ async RL (full-param or single-LoRA)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, TypedDict


@dataclass(frozen=True)
class RLContext:
    """What one async-RL run trains: a single LoRA adapter, or the whole model.

    ``adapter_name`` is the discriminator.  A non-empty name means single-LoRA
    (the sampler loads that adapter on top of the frozen base); ``None`` means
    full-param (the sampler generates from the synced full weights, no adapter).
    Everything downstream keys off this and the ``adapter_path`` on
    :class:`RolloutPolicy`, so no separate context-type flag is needed.
    """

    tenant_id: str
    training_run_id: str
    base_model_id: str
    adapter_name: str | None = None
    tool_profile: str = 'default'

    def __post_init__(self) -> None:
        if self.adapter_name is not None and not (isinstance(self.adapter_name, str) and self.adapter_name):
            raise ValueError(
                f'adapter_name must be None (full-param) or a non-empty string, got {self.adapter_name!r}')

    @property
    def policy_slot(self) -> str:
        """The key/path component identifying the trained policy: the adapter name, or ``full_param``."""
        return self.adapter_name or 'full_param'

    @property
    def key(self) -> str:
        return f'{self.tenant_id}/{self.training_run_id}/{self.policy_slot}'

    def partition_id(self, step: int) -> str:
        return f'{self.key}/train_{step}'


# Backward-compatible alias: ``RLContext`` generalizes the former ``LoraContext``
# (it now also describes full-param runs), so existing callers and tests keep working.
LoraContext = RLContext


@dataclass(frozen=True)
class RolloutPolicy:
    """The immutable policy snapshot used by one rollout group."""

    context_key: str
    adapter_name: str | None
    version: int
    adapter_path: str | None


@dataclass(frozen=True)
class PartitionAdmission:
    """Control-plane admission result for one complete training-data partition.

    A partition is only a training-data batch. Its prompt groups may be
    generated by different policy snapshots.
    """

    context: RLContext
    partition_id: str
    step: int
    target_groups: int
    num_generations: int
    created_order: int

    @property
    def sample_count(self) -> int:
        return self.target_groups * self.num_generations


@dataclass
class PromptGroup:
    """A prompt and the BatchMeta descriptor reserved for its generated samples."""

    context: RLContext
    partition: PartitionAdmission
    group_id: str
    prompt: dict[str, Any]
    batch_meta: Any

    @property
    def partition_id(self) -> str:
        return self.partition.partition_id

    @property
    def num_samples(self) -> int:
        return self.partition.num_generations


@dataclass
class PreparedPartition:
    """Partition prepared in TQ and ready for sampler submission."""

    admission: PartitionAdmission
    groups: tuple[PromptGroup, ...]
    sampling_params: Any


@dataclass
class ClaimedBatch:
    """A TQ-consumed batch and the BatchMeta descriptor selecting its samples."""

    admission: PartitionAdmission
    data: Any
    batch_meta: Any
    sample_tags: tuple[dict[str, Any], ...] = ()


class RolloutOutput(TypedDict, total=False):
    logprobs: list[float]
    rewards: float
    completion_length: int
    generation_idx: int
    rollout_policy_version: int
    rollout_adapter_path: str | None
    rollout_policy_versions: list[int]
    initial_policy_version: int
    final_policy_version: int
    policy_version_span: int
